index:
    path: /
    controller: App\Controller\DefaultController::index
accueil:
    path: /accueil
    controller: App\Controller\DefaultController::accueil
activites:
    path: /activites
    controller: App\Controller\DefaultController::activites
